format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$c\
$cmake\
$python\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""

add_newline = false 

[c]
symbol = "󰙲 "
format = '[$symbol($version(-$name) )]($style)'
detect_extensions	= ['c', 'cpp', 'h', 'hpp']

[cmake]
format = '[$symbol($version )]($style)'

[cmd_duration]
format = '[󰄉 $duration]($style) '

[directory]
truncation_symbol = '…/'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[hostname]
ssh_symbol = " "

[line_break]
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[python]
symbol = "󰌠 "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

