live_config_reload = true

[env]
TERM = "alacritty-direct"

[window]
opacity = 0.80
startup_mode = "Maximized"    # "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
title = "Alacritty"
dynamic_title = false
decorations_theme_variant = "Dark"
resize_increments = true
option_as_alt = "OnlyLeft"

[scrolling]
history = 100000

[font]
#normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
normal = { family = "UbuntuSansMono Nerd Font", style = "Regular" }
size = 12.0
builtin_box_drawing = false

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
